import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Alert from '@/components/Alert'
import "@/styles/globals.css";
import { MainProvider } from "@/contexts/MainContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
return (
    <html lang="en">
        <body className={inter.className}>
            <MainProvider>
                <Alert />
                {children}
            </MainProvider>
        </body>
    </html>
);
}
