import type { Metadata } from "next";
import { MainProvider } from "@/contexts/MainContext";

import Alert from '@/components/Alert'

import "@/styles/globals.css";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
return (
    <html lang="en">
        <body >
            <MainProvider>
                <Alert />
                {children}
            </MainProvider>
        </body>
    </html>
);
}
